# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa7834894c158919bf7e86ab6b6c37fab3d49f4852e746294c8a905aed6a2707cc9ddb52226a0fb837b116493bf4bdb817a921b9cf234ad05f09ac5f2bd96619

test:
  secret_key_base: f289424d7e234ddd5be045668f374f0494e9940ea24c28cbc1a2dcefe8faf5967118ee04d62a1d55e890f64399a0a2fbb5916766b9641d9d1fcdf3233a6f6b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
